### ISSUE TITLE
iOS unified problem? Failed to resolve Foundation.NSDate

### ISSUE THREAD

**Issue by irwincollin** [sbondini/Xamarin.LocalNotifications#6]
When I attempted to use this plugin, I got the following error on compilation:

MTOUCH: Error MT2002: Failed to resolve "Foundation.NSDate Foundation.NSDate::op_Implicit(System.DateTime)" reference from "Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065" (MT2002) (App.iOS)

**Comment by irwincollin** [comment]
Something like this should fix it:

```
private UILocalNotification createNativeNotification (LocalNotification notification)
        {
            DateTime time = notification.NotifyTime;
            NSDate convertedTime = new NSDate ().AddSeconds (time.Ticks * TimeSpan.TicksPerSecond);
            var nativeNotification = new UILocalNotification {
                AlertAction = notification.Title,
                AlertBody = notification.Text,
                FireDate = convertedTime,
                UserInfo = NSDictionary.FromObjectAndKey (NSObject.FromObject (notification.Id), NSObject.FromObject (NotificationKey))
            };

            return nativeNotification;
        }
```

**Comment by b099l3** [comment]
Im getting the same error:

> MTOUCH: error MT2002: Failed to resolve "Foundation.NSDate >Foundation.NSDate::op_Implicit(System.DateTime)" reference from "Xamarin.iOS, Version=0.0.0.0, >Culture=neutral, PublicKeyToken=84e04ff9cfb79065"

Any news on a update to the nuget package? Using the fork from @juancarlosbaezpozos https://github.com/juancarlosbaezpozos/Xamarin.LocalNotifications/commit/7d8bc9bed258698da082ddd78a06e4c454f2c1cd with some modifications on the extensions from here http://developer.xamarin.com/guides/cross-platform/macios/unified/#Converting_DateTime_to_NSDate

**Comment by ilchenkob** [comment]
Fixed.

**Comment by kgerken** [comment]
I'm still experiencing this problem, I'm using the latest (and only) nuget package (1.0.0) - was the package updated with the fix?
